### ISSUE TITLE
Can you tag a release so I can use with Swift package manager version rules?

### ISSUE THREAD

**Issue by PaulSolt** [funky-monkey/IsoCountryCodes#13]
I'd like to use this with the version to keep track of any changes.

You're listing 1.0 on the main readme, but there isn't a tagged version.

Can you add a version 1.0 tagged release?

**Comment by PaulSolt** [comment]
Workaround is to use the SHA `e6a43cf4a08e67eb136a3069735df1ac68f4aaea`

![Xcode Swift Package Manager Dependency](https://user-images.githubusercontent.com/371902/84599482-642c8280-ae40-11ea-81a1-47a75d86c22a.png)

**Comment by funky-monkey** [comment]
Hi @PaulSolt, 

Sorry this took a bit longer.
You can find version 1.0 under the [1.0 tag](https://github.com/funky-monkey/IsoCountryCodes/tree/1.0)

Enjoy!

Sidney

**Comment by PaulSolt** [comment]
Thanks!

**Comment by nakp** [comment]
Hey, the tag actually [needs to use semver](https://developer.apple.com/documentation/swift_packages/version) and it has to be 1.0.0

You can tag the same commit under 1.0.0 and delete the old one 👍

**Comment by funky-monkey** [comment]
Done
